services:
  go-pi-irrigation:
    build: .
    image: jhawk7/go-pi-irrigation
    restart: always
    env_file:
      - .env
    devices:
      #mount i2c bus from pi for temp device
      - "/dev/i2c-1:/dev/i2c-1"